name: hikewise
description: "A mobile application for hiking trail recommendation in Terengganu using Hybrid Algorithms."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  
  # Backend & Authentication 
  supabase_flutter: ^2.6.0
  google_sign_in: ^6.2.1

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # Maps & Navigation (Switched to OpenStreetMap)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.0

  # State Management & UI Enhancement
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/